project:
  type: website
  output-dir: docs

website:
  title: "Demosite Database"
  navbar:
    left:
      - href: index.qmd
        text: Home
      # - about.qmd
      - favorites.qmd
      - r-dashboard.qmd
      - python-nb-dashboard.ipynb

format:
  html:
    theme: sandstone
    css: styles.css
    toc: true



