project:
  type: website
  output-dir: docs

website:
  title: "Demosite Database"
  navbar:
    left:
      - href: index.qmd
        text: Home
      # - about.qmd
      - favorites.qmd
      - r-dashboard.qmd
      - python-nb-dashboard.ipynb
      - href: python-dashboard-text.qmd
        text: The Real Dashboard
      - full-dash-tutorial.qmd
    tools:
      - icon: linkedin
        href: https://www.linkedin.com/in/carl-klein
      - icon: github
        href: https://github.com/clickityKlein

format:
  html:
    theme: sandstone
    css: styles.css
    toc: true



